apiVersion: apps/v1
kind: Deployment
metadata:
  name: aspnetaks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aspnetaks
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: aspnetaks
    spec:
      nodeSelector:
        "kubernetes.io/os": linux
      containers:
        - name: aspnetaks
          image: weyaoimagesacr.azurecr.io/aspnetaks
          ports:
            - containerPort: 80
            - containerPort: 443
          resources:
            requests:
              cpu: 250m
            limits:
              cpu: 500m
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: Production
---
apiVersion: v1
kind: Service
metadata:
  name: aspnetaks-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      name: http
      targetPort: 80
    - port: 443
      name: https
      targetPort: 443
  selector:
    app: aspnetaks
