version: "3.9"
services:
    app:
        build: .
        container_name: webapp
        ports:
            - "8080:80"
            - "8083:443"
        environment:
            - ASPNETCORE_ENVIRONMENT=Production
            - ASPNETCORE_URLS=https://+:443;http://+:80
            - ASPNETCORE_Kestrel__Certificates__Default__Password=123
            - ASPNETCORE_Kestrel__Certificates__Default__Path=/source/cert/aspnetapp.pfx
        depends_on:
            - db
        networks:
            - net1
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: db
        environment:
            MSSQL_SA_PASSWORD: "@Passw0rd"
            ACCEPT_EULA: "Y"
        ports:
            - "1433:1433"
        networks:
            - net1
networks:
    net1: